[build]
  publish = "build"
  command = "npm run build"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18.19.0"
  CI = "false"
  GENERATE_SOURCEMAP = "false"
  SECRETS_SCAN_ENABLED = "false"

[context.production.environment]
  NODE_ENV = "production"
  GENERATE_SOURCEMAP = "false"

[context.deploy-preview.environment]
  NODE_ENV = "development"
  
[context.branch-deploy.environment]
  NODE_ENV = "development"

# Redirect rules for SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# API routes for serverless functions
[[redirects]]
  from = "/api/rag/*"
  to = "/.netlify/functions/openai-file-search"
  status = 200

# Enhanced security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"  
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' https://*.auth0.com https://cdn.auth0.com https://api.openai.com 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; connect-src 'self' https://api.openai.com https://api.groq.com https://*.auth0.com https://*.auth0.io https://*.netlify.app https://ingesteer.services-prod.nsvcs.net; font-src 'self'; frame-src https://*.auth0.com blob:; worker-src 'self' blob:; object-src 'none';"

# Cache static assets
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Function settings - Updated for ES Modules
[functions]
  external_node_modules = ["mammoth", "jsonwebtoken", "jwks-rsa"]
  node_bundler = "esbuild"
  directory = "netlify/functions"

# Environment variables needed for functions (add these in Netlify dashboard)
# OPENAI_API_KEY = "sk-..."